#!/usr/bin/env bash

set -euxo pipefail

# bash_shared () {
#     echo ". $HOME/.nix-profile/etc/profile.d/nix.sh" >> "$HOME/.bashrc"
#     if [ -d "$HOME/miniconda3" ]; then
#         echo ". $HOME/miniconda3/etc/profile.d/conda.sh" >> "$HOME/.bashrc"
#     fi
# }

vim_shared () {
    mkdir -p "$HOME/.vim/colors"
    mkdir -p "$HOME/.vim/syntax"
    mkdir -p "$HOME/.vim/after/syntax"

    f () {
        if [ ! -f "$HOME/.vim/syntax/$2" ]; then
            curl "$GIT_URL/$1" > "$HOME/.vim/syntax/$2"
        fi
    }

    f "futhark-vim/simplify/syntax/fut.vim"                 "fut.vim"
    f "haskell.vim/master/syntax/haskell.vim"               "haskell.vim"
    f "vim-javascript-syntax/master/syntax/javascript.vim"  "javascript.vim"
    f "vim-nix/master/syntax/nix.vim"                       "nix.vim"
    f "stan.vim/master/syntax/stan.vim"                     "stan.vim"
    f "typescript-vim/master/syntax/typescript.vim"         "typescript.vim"
    f "rust.vim/master/syntax/rust.vim"                     "rust.vim"
    f "vim-crystal/master/syntax/crystal.vim"               "crystal.vim"

    if [ ! -f "$HOME/.vim/after/syntax/c.vim" ]; then
        curl "$GIT_URL/c-syntax.vim/master/after/syntax/c.vim" \
            > "$HOME/.vim/after/syntax/c.vim"
    fi

    if [ ! -f "$HOME/.vim/colors/gruvbox.vim" ]; then
        curl "$GIT_URL/gruvbox/master/colors/gruvbox.vim" > \
            "$HOME/.vim/colors/gruvbox.vim"
    fi

    if [ ! -f "$HOME/.vim/syntax/glsl.vim" ]; then
        curl "https://www.vim.org/scripts/download_script.php?src_id=3194" > \
            "$HOME/.vim/syntax/glsl.vim"
    fi

    if [ ! -f "$HOME/.vim/after/syntax/glsl.vim" ]; then
        cp "$WD/vim/after_syntax_glsl.vim" "$HOME/.vim/after/syntax/glsl.vim"
    fi

    if [ ! -f "$HOME/.vim/after/syntax/ocaml.vim" ]; then
        cp "$WD/vim/after_syntax_ocaml.vim" "$HOME/.vim/after/syntax/ocaml.vim"
    fi

    for x in python javascript stan typescript; do
        if [ ! -f "$HOME/.vim/after/syntax/$x.vim" ]; then
            cp "$WD/vim/match_function.vim" "$HOME/.vim/after/syntax/$x.vim"
        fi
    done
}

if [ "$(uname -s)" = "Darwin" ]; then
    # cp "$WD/bash/profile"       "$HOME/.bash_profile"
    # cp "$WD/bash/darwin.bashrc" "$HOME/.bashrc"
    # bash_shared
    vim_shared
    cp "$WD/vim/darwin.vimrc"   "$HOME/.vimrc"
    # cp "$WD/vim/bla.vim"        "$HOME/.vim/colors/bla.vim"
    # if [ ! -d "$HOME/.config/alacritty" ]; then
    #     mkdir -p "$HOME/.config/alacritty"
    # fi
    # cp "$WD/alacritty/alacritty.yml"    "$HOME/.config/alacritty/alacritty.yml"
    # if [ ! -f "$HOME/.gitconfig" ]; then
    #     echo Update "$HOME/.gitconfig" with \`user.name\` and \`user.email\`!
    #     cp "$WD/git/darwin.config"         "$HOME/.gitconfig"
    # fi
else
    if [ ! -f "$HOME/.vim/colors/nord.vim" ]; then
        curl "$GIT_URL/nord-vim/develop/colors/nord.vim" > \
            "$HOME/.vim/colors/nord.vim"
    fi
    # cp "$WD/bash/linux.bashrc"  "$HOME/.bashrc"
    # bash_shared
    # echo "" | cat "/etc/skel/.bashrc" - "$HOME/.bashrc" > "$WD/tmp.bashrc"
    # mv "$WD/tmp.bashrc"         "$HOME/.bashrc"
    vim_shared
    cp "$WD/vim/linux.vimrc"    "$HOME/.vimrc"
    # cp "$WD/vim/blx.vim"        "$HOME/.vim/colors/bla.vim"
    # if [ ! -d "$HOME/.config/alacritty" ]; then
    #     mkdir -p "$HOME/.config/alacritty"
    # fi
    # cp "$WD/alacritty/alacritty.yml"    "$HOME/.config/alacritty/alacritty.yml"
    # cp "$WD/i3/i3.config"       "$HOME/.config/i3/config"
    # cp "$WD/i3/i3status.config" "$HOME/.config/i3status/config"
    # if [ ! -d "$HOME/bin" ]; then
    #     mkdir "$HOME/bin"
    # fi
    # cp "$WD/bin/cbacklight"     "$HOME/bin/cbacklight"
    # cp "$WD/i3/fehbg"           "$HOME/.fehbg"
    # cp "$WD/i3/redshift"        "$HOME/.redshift"
    # if [ ! -f "$HOME/.gitconfig" ]; then
    #     echo Update "$HOME/.gitconfig" with \`user.name\` and \`user.email\`!
    #     cp "$WD/git/linux.config"         "$HOME/.gitconfig"
    # fi
fi
# cp "$WD/tmux/tmux.conf"         "$HOME/.tmux.conf"
if [ ! -f "$HOME/.config/nvim/init.vim" ]; then
    mkdir "$HOME/.config/nvim"
    cp "$WD/vim/init.vim" "$HOME/.config/nvim/init.vim"
fi
