#
# ~/.bash_profile
#

[[ -f ~/.bashrc ]] && . ~/.bashrc

if [ -e /home/albert/.nix-profile/etc/profile.d/nix.sh ]; then
    . /home/albert/.nix-profile/etc/profile.d/nix.sh
fi # added by Nix installer
